#!/usr/bin/python3
import sys
from steamlinuxchecker import get_steam_id, check_steam_user


def main():
    usage = f"""
    Usage:
        {sys.argv[0]} profile_url|vanity_name|steam_id

        vanity_name
            Part of the Steam profile URL after `/id/`.

        steam_id
            Number in the Steam profile URL after `/profiles/`.

        profile_url
            I believe in your intelligence.
    """

    if len(sys.argv) != 2 or sys.argv[1] in ('-h', '--help'):
        raise SystemExit(usage)

    user_id = sys.argv[1]
    check_steam_user(get_steam_id(user_id), True)


if __name__ == '__main__':
    main()
