#!/usr/bin/python3
import sys
from time import sleep

import requests
from steamlinuxchecker import get_group_id, get_group_members, check_steam_user, print_scan_summary


def main():
    usage = """
    Usage:
        {} group_name|guid

        group_name
            Part of the group URL after `/groups/`.

        guid
            Steam internal value `groupID64`.
    """.format(sys.argv[0])

    if len(sys.argv) != 2 or sys.argv[1] in ('-h', '--help'):
        raise SystemExit(usage)

    group_id = get_group_id(sys.argv[1])

    for id in get_group_members(group_id):
        print_scan_summary(check_steam_user(id, False))
        sleep(1)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit("\nExiting...\n");
